# Generated by Django 5.2.8 on 2025-12-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff_permissions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffpermission',
            name='unique_staff_module',
        ),
        migrations.AlterUniqueTogether(
            name='staffpermission',
            unique_together={('staff', 'module')},
        ),
    ]
