# Generated by Django 5.2.8 on 2025-11-14 16:54

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_orderhistorypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=restaurant.models.generate_order_id, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_id',
            field=models.CharField(editable=False, max_length=8),
        ),
    ]
