# Generated by Django 5.2.8 on 2025-11-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_alter_order_order_id_alter_orderhistory_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Cooking'), ('ready', 'Ready'), ('on_the_way', 'On The Way'), ('ready_to_pickup', 'Ready to Pickup'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_type',
            field=models.CharField(choices=[('table', 'Table'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='table', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Cooking'), ('ready', 'Ready'), ('on_the_way', 'On The Way'), ('ready_to_pickup', 'Ready to Pickup'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
    ]
