# Generated by Django 5.2.8 on 2025-11-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_alter_order_status_alter_orderhistory_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for order cancellation', null=True),
        ),
    ]
