# Generated by Django 5.2.8 on 2025-11-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_order_delivery_address_order_delivery_building_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatuslog',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='orderstatuslog',
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderHistoryStatus',
        ),
        migrations.DeleteModel(
            name='OrderStatusLog',
        ),
    ]
