# Generated by Django 6.0 on 2025-12-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_orderhistory_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('fonepay', 'Fonepay'), ('bank', 'Bank'), ('khalti', 'Khalti'), ('ipay', 'Ipay'), ('esewa', 'Esewa'), ('imepay', 'Imepay'), ('connectips', 'Connectips')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderhistorypayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('fonepay', 'Fonepay'), ('bank', 'Bank'), ('khalti', 'Khalti'), ('ipay', 'Ipay'), ('esewa', 'Esewa'), ('imepay', 'Imepay'), ('connectips', 'Connectips')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('fonepay', 'Fonepay'), ('bank', 'Bank'), ('khalti', 'Khalti'), ('ipay', 'Ipay'), ('esewa', 'Esewa'), ('imepay', 'Imepay'), ('connectips', 'Connectips')], max_length=50),
        ),
    ]
