# Generated by Django 5.2.8 on 2026-02-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_add_kmeans_clustering_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('fonepay', 'Fonepay'), ('bank', 'Bank'), ('khalti', 'Khalti'), ('esewa', 'Esewa'), ('imepay', 'Imepay'), ('connectips', 'Connectips')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderhistorypayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('fonepay', 'Fonepay'), ('bank', 'Bank'), ('khalti', 'Khalti'), ('esewa', 'Esewa'), ('imepay', 'Imepay'), ('connectips', 'Connectips')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('fonepay', 'Fonepay'), ('bank', 'Bank'), ('khalti', 'Khalti'), ('esewa', 'Esewa'), ('imepay', 'Imepay'), ('connectips', 'Connectips')], max_length=50),
        ),
    ]
